apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-deployment
  namespace: flux-system
spec:
  interval: 5m
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-k8s-deployment
  # Настройка на namespace в самите ресурси, които Flux ще синхронизира
  targetNamespace: default
