apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: default  # Тук се добавя namespace, например "default"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: quay.io/stefanprodan/podinfo:latest
        ports:
        - containerPort: 9898
