apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10m
  path: "./podinfo"  
  sourceRef:
    kind: GitRepository
    name: podinfo
  prune: true  