apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/AlexChavdarov/podinfo-repo.git
  ref:
    branch: main  # Указваме, че искаме да използваме "main" клона
  secretRef:
    name: flux-git-auth
