apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-k8s-deployment
  namespace: default
spec:
  url: https://github.com/AlexChavdarov/flux-k8s-deployment
  ref:
    branch: main
  interval: 5m
