apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-k8s-deployment
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/AlexChavdarov/flux-k8s-deployment
  ref:
    branch: main
