apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m
  path: ./podinfo
  git:
    repoURL: https://github.com/AlexChavdarov/flux-k8s-deployment
    branch: main
  prune: true
