apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m
  path: ./podinfo
  gitRepositoryRef:
    name: flux-k8s-deployment
  prune: true
