apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  resources:
    - podinfo/podinfo.yaml
    - podinfo/deployment.yaml
    - podinfo/service.yaml
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-k8s-deployment
    namespace: flux-system
