apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  sources:
    - kind: GitRepository
      name: flux-k8s-deployment
      interval: 1m
  path: ./podinfo
  prune: true
  interval: 5m
