apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: default  # Указва namespace за Service ресурса
spec:
  ports:
  - port: 9898
    targetPort: 9898
  selector:
    app: podinfo
