apiVersion: v1
kind: Service
metadata:
  name: podinfo
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9898
    - name: https
      port: 443
      targetPort: 9898
  selector:
    app: podinfo
  type: ClusterIP
